config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  resources :users, only: [:index,  :show] do
    resources :posts, only: [:index,  :show, :new, :create, :destroy] do 
      resources :comments, only: [ :new, :index, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #   return unless user.present?
    #   can :read, :all
    return unless user.present?

    if user.role == 'Admin'
      can :manage, :all
    else
      can :manage, Post, author: user
      can :manage, Comment, author: user
      can :read, :all
    end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :comments_counter

  def comments_counter
    post.update!(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_likes_counter

  def update_likes_counter
    post.update!(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy

  def comments_counter
    comments.count
  end

  def likes_counter
    likes.count
  end

  after_save :update_author_posts_counter

  def add_comment(comment)
    comments << comment
  end

  def most_recent_comments()
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_author_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  after_save :most_recent_posts

  def most_recent_posts
    posts.where(author: self).order(created_at: :desc).limit(3)
  end

  def posts_counter
    posts.count
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::API
  respond_to :json
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController
  def index
    @comments = Comment.all.where(author_id: params[:user_id], post_id: params[:post_id])
    render json: @comments
  end

  def create
    request_body = JSON.parse(request.body.read)
    comment = Comment.new(author_id: current_user, post_id: params.require(:post_id), text: request_body['comment'])

    if comment.save
      render json: comment, status: :created
    else
      render json: comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_body
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  def index
    @posts = Post.all.where(author_id: params.require(:user_id))
    render json: @posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password role])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end

  def create
    @comment = Comment.create(author_id: current_user.id, post_id: params[:post_id], text: params[:comment][:text])
    if @comment.save
      redirect_to user_post_path(params[:user_id], params[:post_id]), notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment
    if @comment.destroy
      flash[:success] = 'Comment successful deleted'
      redirect_to user_post_path(@comment.post.author, @comment.post)
    else
      flash[:error] = 'Failed to delete comment'
      redirect_to @comment.post
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(author_id: params[:user_id], post_id: params[:post_id])

    if @like.save
      redirect_to user_post_path(params[:user_id], params[:post_id]), notice: 'Liked 👍'
    else
      redirect_to user_post_path(params[:user_id], params[:post_id]), alert: 'An error occured, please try again!'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:likes, :comments).paginate(page: params[:page], per_page: 2)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.includes(:likes, :comments).find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(author_id: params[:post][:user_id], title:
       params[:post][:title], text: params[:post][:text].gsub(/\r\n?/, '<br>'))

    if @post.save
      redirect_to user_path(params[:post][:user_id]), notice: 'Post was successfully created.'
    else
      render :new
      flash.alert = 'Error!, Post not added!'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    if @post.destroy
      flash[:sucess] = 'post was successfully deleted'
      redirect_to user_posts_path(@post.author)
    else
      flash[:error] = 'Failed to delete post'
      redirect_to user_post_path(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:author_id, :title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(:id).includes(:posts)
  end

  def show
    @user = User.includes(posts: %i[likes comments]).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_create.html.erb
<%= form_with(model: [ @post, Comment.new ], url: user_post_comments_path(user_id: current_user.id, post_id: @post.id), local: true ) do |form| %>
<div class="flex flex-col gap-3  w-full px-10 md:px-80">
	<%= form.text_area :text, hide_label: true, placeholder: "Leave a comment...", class:"border border-gray-100 h-48", required: true %>
	<%= form.submit "Add comment" , class:"text-white bg-blue-700 hover:bg-blue-800 active:bg-blue-900 p-3 px-5 rounded-sm w-40"%>
</div>
<% end %>

app/views/comments/new.html.erb
<%= content_tag :div, class: "post-comments" do %>
	<%= form_with(model: @comment, url: user_post_comments_path(post_id: params[:post_id])) do |form| %>
	<%= form.text_area :text, hide_label: true, placeholder: "Leave a comment...", required: true %>
	<%= form.submit "Add comment" %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render 'shared/header' %>
<section class="border border-gray-200 flex-1 mx-2 gap-4 flex flex-col pb-4">
	<%= render 'shared/user', user: @user %>
	<% @posts.each do |post| %>
		<div class="flex flex-col gap-1">
			<%= render 'shared/post', post: post %>
			<div class="border border-gray-200 p-3 mx-5">
				<% post.most_recent_comments.each do | comment | %>
				<% @user = User.find(comment.author_id) %>
				<p><%= @user["name"] %>: <span><%= comment.text %></span></p>
				<% end %>
			</div>
		</div>
	<% end %>
	<div class=" flex justify-center">
		<%= content_tag :div, class: "digg_pagination" do %>
		<%= will_paginate @posts %>
		<% end %>
	</div>
	
</section>

app/views/posts/new.html.erb
<%= render 'shared/header' %>
<section class="h-screen flex  flex-col justify-center items-center">
	<% if @post.errors.any? %>
	<div>
		<% @post.errors.full_messages.each do |message| %>
		<p><%= message %></p>
		<% end %>
	</div>
	<% end %>
	<div class="flex flex-col gap-5 items-baseline justify-start ">
		<h4>Add your message here:</h4>
		<%= form_for [@user, @post], url:  user_posts_path(current_user), locale: true, method: :post do |form| %>
		<div class="flex flex-col mb-3">
			<label>Title</label>
			<%= form.text_field :title, required: true, autofocus: true, class: "border border-gray-200 rounded-sm p-2" %>
		</div>
		<div class="flex flex-col mb-3">
			<label>Message</label>
			<%= form.text_area :text, required: true, autofocus: true, class: "form-input" %>
		</div>

		<%= form.hidden_field :user_id, value: current_user.id %>
		<%= content_tag :div , class: "flex justify-center gap-3" do %>
		<button
			class="text-white bg-blue-700 hover:bg-blue-800 active:bg-blue-900 p-3 px-5 rounded-sm"><%= link_to "Cancel", user_posts_path(current_user) %></button>
		<%= form.submit "Save Post", class: "text-white bg-blue-700 hover:bg-blue-800 active:bg-blue-900 p-3 px-5 rounded-sm" %>
		<% end %>
		<% end %>
	</div>
</section>

app/views/posts/show.html.erb
<%= render 'shared/header' %>
<section class="flex flex-col gap-3">
	<div class="mt-3">
		<div class="flex justify-between items-center p-3 mx-2 border border-gray-200">
			<h3><%= content_tag :span, "Post # #{@post.id} by #{@post.author.name}" %></h3>
			<%= content_tag :span, "Comments: #{@post.comments_counter}, Likes: #{@post.likes_counter}" %>
		</div>
	</div>
	<div>
		<%= content_tag :div, class: "mx-2 border" do %>
		<%= button_to "🖤 Like", user_post_likes_path(user_id: current_user.id, post_id: @post.id), method: :post %>
		<% end %>
	
	<div class="border mx-2 p-3 flex flex-col gap-3">
		<h2 class="font-bold"><%= @post.title%></h2>
		<span>
			<% if can? :destroy , @post  %>
			<%= button_to "DELETE POST", user_post_path(current_user, @post), method: :delete ,class: "hover:bg-blue-800 duration-90 bg-blue-700 border-blue-700 p-2 text-white rounded-sm text-[11px]"%>
			<%end%>
		</span>
		<p class="title-bio"><%= @post.text %></p>
		<ul>
			<h3>💬 Comments:</h3>
			<% @post.comments.each do|comment|%>
				<li><%= content_tag :span, "#{comment.author.name}: #{comment.text}" %></li>
				<span>
					<% if can? :destroy, comment %>
					<%= button_to "DELETE COMMENT", user_post_comment_path(comment.author, comment.post, comment), method: :delete, class: "hover:bg-blue-800 duration-90 bg-blue-700 border-blue-700 p-2 text-white rounded-sm text-[11px] mt-2" %>
					<% end %>
				</span>
			<%end%>
		</ul>
	</div>
	<div class="px-10">
	<%= render "comments/create", locals: { post_id: @post_id, comment: @comment } %>
	</div>
</section>

app/views/shared/_header.erb
<header class="flex justify-between items-center bg-white border border-gray-200 py-3 px-7">
    <h1 class="text-blue-500 font-bold text-2xl"><%= link_to "Blog App", users_path, class:"hover:bg-blue-800 duration-90 border-blue-700 p-2 px-4 rounded-sm hover:text-white" %></h1>
      <ul class="flex gap-10 items-center">
        <li><%=  button_to "Logout",destroy_user_session_path ,method: :delete, class: "hover:bg-blue-800 duration-90 bg-blue-700 border-blue-700 p-2 text-[12px] text-white rounded-sm" %></li>
</header>

app/views/shared/_nav.erb
<header class="flex justify-between items-center bg-white border border-gray-200 py-3 px-7">
    <h1 class="text-blue-500 font-bold text-2xl"><%= link_to "Blog App", users_path, class:"hover:bg-blue-800 duration-90 border-blue-700 p-2 px-4 rounded-sm hover:text-white" %></h1>
      <ul class="flex gap-10 items-center">
				<li><%= link_to "Create Post", new_user_post_path(current_user), class: "hover:bg-blue-800 duration-90 bg-blue-700 border-blue-700 p-2 text-[12px] text-white rounded-sm" %> </li>
				<li><%=  link_to "Edit Account",edit_user_registration_path(current_user) , class: "hover:bg-blue-800 duration-90 bg-blue-700 border-blue-700 p-2 text-[12px] text-white rounded-sm" %></li>
        <li><%=  button_to "Logout",destroy_user_session_path ,method: :delete, class: "hover:bg-blue-800 duration-90 bg-blue-700 border-blue-700 p-2 text-white rounded-sm text-[12px]" %></li>
      </ul>
      </ul>
</header>

app/views/shared/_post.erb
<div class="border border-gray-200 flex-1 mx-5">
  <div class="flex flex-col gap-3 p-3 px-5">
  <h3 class="text-2xl font-bold hover:text-blue-700 active:text-blue-800 duration-75"><%= link_to post.title, user_post_path(@user, post) %> #<% post.id %> </h3>
  <p><%= "#{post.text.slice(0, 100)}..." %></p>
  <p class="text-right">Comments: <%= post.comments_counter || 0 %>,Likes: <%= post.likes_counter || 0 %></p>
  </div>
</div>

app/views/shared/_user.erb
<div class="flex h-48 items-center p-10 gap-4 border border-gray-200 mx-5 mt-3">
	<div class="h-32 w-32">
		<img class="w-full h-full" src="<%= user.photo %>" alt= <%= user.name %> >
	</div>
	<div class="border border-gray-200 flex-1 flex justify-center p-2 px-5 h-32 flex-col" >
		<h2 class="text-3xl font-bold hover:text-blue-700 active:text-blue-800 duration-75"><%= link_to user.name, user_path(user), class: "user_link" %></h2>
	  <p class="font-medium text-right mt-3"><%= "Number of posts: #{ user.posts_counter || 0}" %></p>
	</div>
</div>

app/views/users/index.html.erb
<%= render "shared/header" %>
<section class="border border-gray-200 flex flex-col gap-3 mx-2 p-3">
	<% @users.each do |user| %>
	<%= render 'shared/user', user:user %>
	<% end %>
</section>

app/views/users/show.html.erb
<%= render "shared/nav" %>
<section class="flex gap-3 flex-col border border-gray-200 mx-2 px-3 pb-5">
	<%= render 'shared/user', user: @user %>
	<div class="flex gap-3 flex-col">	
		<div class="border border-gray-100 p-3 mx-5">
			<h2 class="text-2xl font-bold">Bio</h2>
			<p><%= @user.bio %></p>
		</div>
		<% @user.most_recent_posts.each do |post| %>
		 <%= render 'shared/post', post:post %>
		<%end %>
	</div>
	<div class="text-center">
		<button class="text-white bg-blue-700 hover:bg-blue-800 active:bg-blue-900 p-3 px-5 rounded-sm"><%= link_to "see all posts", user_posts_path(@user) %></button>
	</div>
</section>